### ISSUE TITLE
how can i get ["electronegativity", "hardness", "vdWaalsVolume"] in calculate_rdfs.py?

### ISSUE THREAD

**Issue by Matgen-project** [BurnerJ/descriptors-and-pytorch-models-for-low-pressure-co2-adsorption-in-mofs#1]

**Comment by BurnerJ** [comment]
Hi,
The element information is located in atomic_property_dict.py in the CalculateRDFs directory. If you add atomic_property_dict.py to the same directory in which you're running calculate_rdfs.py, it will locate the required element information. You can alternatively modify the dictionary to include whatever atomic attributes you would like.
Please let me know if you need any additional clarification.

**Comment by Matgen-project** [comment]
My own cif file have some files includes some element which information are not shown in  atomic_property_dict.py,such as U(Uranium),where can I can get U's  electronegativity,hardness and vdWaalsVolume?
